name: log github events

on:
  pull_request:
    types: [opened, closed]
    branches: [main, master]

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      COMMIT_LOG_API: ${{ secrets.COMMIT_LOG_API }}
      GITHUB_LOGIN: ${{ github.actor }}
      PR_CREATED_AT: ${{ github.event.pull_request.created_at }}
      PR_CLOSED_AT: ${{ github.event.pull_request.closed_at }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js (upgrade to node 20)
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install pipenv and dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --python /Users/haoyuansong/micromamba/bin/python3.9
      

    - name: Debugging Repository URL
      run: |
        REPOSITORY_URL="https://github.com/agiledev-students-fall2024/4-final-project-while-we-were-dreaming"
        echo "Repository URL: ${REPOSITORY_URL}"

    - name: Log pull request opened
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      run: |
        REPOSITORY_URL="https://github.com/agiledev-students-fall2024/4-final-project-while-we-were-dreaming"
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -t pull_request_opened -d ${PR_CREATED_AT} -u ${GITHUB_LOGIN} -o commit_stats.csv -v ${COMMIT_LOG_API}

    - name: Log pull request closed and merged
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        REPOSITORY_URL="https://github.com/agiledev-students-fall2024/4-final-project-while-we-were-dreaming"
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -t pull_request_merged -d ${PR_CLOSED_AT} --merged -o commit_stats.csv -v ${COMMIT_LOG_API}

    - name: Log pull request closed without merge
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
      run: |
        REPOSITORY_URL="https://github.com/agiledev-students-fall2024/4-final-project-while-we-were-dreaming"
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -t pull_request_closed -d ${PR_CLOSED_AT} -u ${GITHUB_LOGIN} -o commit_stats.csv -v ${COMMIT_LOG_API}

    - name: Log push
      if: github.event_name == 'push'
      run: |
        REPOSITORY_URL="https://github.com/agiledev-students-fall2024/4-final-project-while-we-were-dreaming"
        echo $COMMITS > commits.json
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -t push -i commits.json -o commit_stats.csv -v ${COMMIT_LOG_API}
